### PR TITLE
Revert "Re-applying Optimizations"

### PR DESCRIPTION
**Pull request by ormsbee**
@cpennington: The tests passed on the PR, but my change seems to have broken the build on master. Are the tests non-deterministic?

Anyhow, I'm reverting until I can figure it out.

### CODE REVIEW

**Comment by ormsbee** [comment]
https://travis-ci.org/edx/opaque-keys/builds/199478565

**Comment by cpennington** [comment]
The tests use hypothesis, so they will generate new test cases every time. If you hit a test case failure that's interesting, it's good to add it to the set of examples that decorate each test (those will all be checked in every test run).

**Comment by cpennington** [comment]
That said, I don't think the second key should have parsed at all: `i4x://-/-/-/-@-/` (which should be equivalent to `i4x://org/course/category/block_id@version/`. The trailing slash shouldn't be allowed.

**Comment by ormsbee** [comment]
Okay, so picking this up again after a long, long hiatus. :-P I reverted immediately when I saw this failure, but it looks like it's something that happens in master as well when this test case is passed in. Investigating why this isn't rejected.

**Comment by cpennington** [comment]
That's the lovely thing about hypothesis... You can't be sure it's actually found all the things it could possibly find...

**Pull request merged**
