### PR TITLE
Deploying to PyPI/Version Update

### LINKED ISSUE #59: Release to PyPI
* Create a new version
* Update Travis to automatically [release new tags to PyPI](https://docs.travis-ci.com/user/deployment/pypi/) (this may require renaming the package to edx-opaque-keys to avoid confusion)

### PR DESCRIPTION
**Pull request by clintonb**
Fixes #59

### CODE REVIEW

**Comment by clintonb** [comment]
FYI @cpennington. I will also create a new tag so that can cleanup external references that continue to use various git hashes.

**Comment by cpennington** [comment]
Ok. Are you also going to push to PyPI?

**Comment by clintonb** [comment]
I would like to, and created #59 to do so. However, the last question about naming is what has stopped me. Should we continue calling this package `opaque-keys` or use a more transparent name, `edx-opaque-keys` that makes it clear this is intended for use with edX code?

I can go either way. A rename should not pose much developer pain. Anyone wanting to use the PyPI version would need to update requirements.txt anyway. They'd just use the new name instead of the old one.

(Puns intended!)

**Comment by cpennington** [comment]
I'd be fine with clarifying the package name by prefixing edx.

**Comment by clintonb** [comment]
Good...because it turns out pip doesn't like `setup.py`'s `dependency_links`, so we will need to deploy to PyPI.

**Pull request merged**
